name: Auto PR2

on: 
  schedule:
    - cron:  '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9

      - name: Install curl and jq
        run: sudo apt update && sudo apt install curl jq -y

      - name: Check latest WinPython version
        id: checkupdates
        continue-on-error: true
        run: |
          pip install requests
          python check_updates.py
          echo "::set-output name=exitcode::$?"
      
      - name: Update WinPython version
        if: "${{ steps.checkupdates.outputs.exitcode }}" == "1"
        run: curl -sL https://api.github.com/repos/winpython/winpython/releases/latest | jq -r ".tag_name" > winpython_version.txt

      - name: Create PR no py updates
        if: "${{ steps.checkupdates.outputs.exitcode }}" = "1"
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update WinPython
          title: 'WinPython Update'
          body: |
            A new version of WinPython was found. 
            The new WinPython version is using the same Python version as we are using now.
            > Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            WinPython Update
          team-reviewers: |
            owners
            maintainers
          draft: false

      - name: Create PR with py updates
        if: "${{ steps.checkupdates.outputs.exitcode }}" == "2"
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update WinPython
          title: 'WinPython Update - Python version changed'
          body: |
            A new version of WinPython was found. 
            **The new WinPython version is using A NEW Python version: you need to manually update it**.
            > Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            WinPython Update
          team-reviewers: |
            owners
            maintainers
          draft: false
