name: Show Windows Packages

on: push

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2.3.4
      - name: run powershell script
        run: .\winpython.ps1
      