name: Release PanoptoSync

on: 
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: run powershell script
        run: .\winpython.ps1
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Automated build - ${{ steps.date.outputs.date }}
          body: This is an automated build
          tag_name: ${{ steps.date.outputs.date }}
          files: |
            PanoptoSync.exe
